### ISSUE TITLE
Subir proyecto a la web

### ISSUE THREAD

**Issue by CristianJulio** [hguzman/Planeadores#101]

**Comment by JhanCarlos-117** [comment]
Presentó problemas de compilación de los assets al momento de subir a la master de heroku

**Comment by JhanCarlos-117** [comment]
Error de compilación solucionado los archivos fueron montados a la master de heroku, pero al momento de abrir la app sale el siguiente error (We're sorry, but something went wrong.
If you are the application owner check the logs for more information.)

**Comment by JhanCarlos-117** [comment]
Proyecto subido a heroku enlace (https://limitless-gorge-16676.herokuapp.com/usuarios/sign_in) Falta la creacion de usuario para ingresar

**Comment by JhanCarlos-117** [comment]
Usuario creado permite crear las planeaciones y transacciones pero al momento de registrar un agente lo registra pero muestra un error por causa de correo que se le envía, cree un correo y lo agregue pero me dice que el nombre de usuario y contraseña no son aceptados

**Comment by JhanCarlos-117** [comment]
Proyecto subido a Heroku finalizado  enlace (https://limitless-gorge-16676.herokuapp.com/usuarios/sign_in)
