### ISSUE TITLE
Diagramas de secuencia

### ISSUE THREAD

**Issue by CristianJulio** [hguzman/Planeadores#152]
# Por hacer
- Crear diagramas de secuencias
- Agregar el archivo de Star UML o del programa/página que se use a la carpeta Documentación
- Generar una imagen del diagrama y agregarla a la landing page

**Comment by ZohairCR** [comment]
Ya agregue los diagramas de secuencia

**Comment by hguzman** [comment]
No se ha terminado con elrequerimiento

**Comment by ZohairCR** [comment]
Ya agregué los diagramas de secuencia que faltaban.
