### ISSUE TITLE
Corregir documento de pruebas

### ISSUE THREAD

**Issue by CristianJulio** [hguzman/Planeadores#184]
- Corregir Documento de pruebas
- Subir el documento a la landig page
- Subir el documento a la carpeta documentación del repositorio

**Comment by JhanCarlos-117** [comment]
Documento de plan de prueba corregido y se cambio de plantilla

**Comment by JhanCarlos-117** [comment]
Documento de plan de pruebas subido a la documentación y issues cedido @CristianJulio
