### ISSUE TITLE
Realizr pruebas unitarias con selenium

### ISSUE THREAD

**Issue by CristianJulio** [hguzman/Planeadores#205]

**Comment by ZohairCR** [comment]
Me encuentro realizando  las pruebas del aplicativo

**Comment by ZohairCR** [comment]
![Sin tí](https://user-images.githubusercontent.com/60449108/95241009-d3085f80-07d2-11eb-82d6-d5f00efd03f0.png)

**Comment by ZohairCR** [comment]
Ya envié las respectivas pruebas

**Comment by ZohairCR** [comment]
Realizado la parte de las pruebas con Selenium
