### ISSUE TITLE
Realizar pruebas unitarias con Rspec

### ISSUE THREAD

**Issue by CristianJulio** [hguzman/Planeadores#206]

**Comment by JhanCarlos-117** [comment]
Investigando sobre las pruebas unitarias, ya he encontrado como hacer ejemplos pero no se aun como implementarlas en el proyecto

**Comment by JhanCarlos-117** [comment]
![Captura de pantalla (86)](https://user-images.githubusercontent.com/60632109/94744993-7ffc5b80-033f-11eb-9c40-fa7d5f7a37cb.png)

**Comment by JhanCarlos-117** [comment]
Pruebas unitarias realizadas de mi parte
