### ISSUE TITLE
Actualizar maqueteado de la landing page

### ISSUE THREAD

**Issue by CristianJulio** [hguzman/Planeadores#231]
**Describe the bug**
El maqueteado que está montado en el repositorio está desactualizado.

**To Reproduce**
Pasos para reproducir el problema:
1. Go to 'https://github.com/hguzman/Planeadores/blob/master/Documentaci%C3%B3n/Maquetado%20(Landing%20Page)/Landing%20Page%20(Maquetado).bmpr'
2. Click on 'Download'
3. Abre el archivo con balsamiq

**Expected behavior**
Que el maqueteado concuerde con la landing page

**Screenshots**
None

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CristianJulio** [comment]
![Uploading Captura.PNG…]()

**Comment by JhanCarlos-117** [comment]
Actualización casi terminada
